version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cakeapp
      POSTGRES_USER: cakeuser
      POSTGRES_PASSWORD: cakepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cakeuser -d cakeapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://cakeuser:cakepass@postgres:5432/cakeapp
      JWT_SECRET: your-secret-key-here
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000

volumes:
  postgres_data:
